name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  IMAGE_REPO: fishtrackerbackend
  REGISTRY: crfishtracker.azurecr.io
  WEBAPP_NAME: waFishTrackerApi
  AZURE_SUBSCRIPTION: scFishTracker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=${{ github.run_number }}
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:$IMAGE_TAG .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
