name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  IMAGE_REPO: fishtrackerbackend
  REGISTRY: crfishtracker.azurecr.io
  WEBAPP_NAME: waFishTrackerApi

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.build-image.outputs.imageTag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      run: az acr login --name crfishtracker

    - name: Build and push Docker image
      id: build-image
      run: |
        IMAGE_TAG=${{ github.run_number }}
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:$IMAGE_TAG .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:$IMAGE_TAG
        echo "imageTag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ needs.build.outputs.imageTag }}
